version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: BoraEncontros.WebApi/Dockerfile
    container_name: BoraEncontros.WebApi
    ports:
      - "2001:8080"  # HTTP
    env_file: .env


  workers:
    build:
      context: .
      dockerfile: BoraEncontros.Workers/Dockerfile
    container_name: BoraEncontros.Workers
    ports:
      - "3001:8080"
    env_file: .env
