version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: BoraEncontros.WebApi/Dockerfile
    container_name: BoraEncontros.WebApi
    ports:
      - "1000:1000"  # HTTP
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:1000"
      
      ConnectionStrings__BoraEncontros: "Server=tcp:bora-db.database.windows.net,1433;Initial Catalog=bora-encontros;Persist Security Info=False;User ID=bora;Password={password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"      
      GoogleCalendarSettings__ApplicationName: "BoraEncontros"
      GoogleCalendarSettings__ClientId: "{clientId}"
      GoogleCalendarSettings__ClientSecret: "{clientSecret}"
      GoogleCalendarSettings__TokenFolder: "token.json"
