version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: BoraEncontros.WebApi/Dockerfile
    container_name: BoraEncontros.WebApi
    ports:
      - "1000:1000"  # HTTP
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:1000"
