name: Deploy boraencontros-workers to Azure Function App

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4

    - name: Set up .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: dotnet publish (restore, build e publish)
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/boraencontros-workers

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_BORA_CREDS }}    

    - name: Deploy boraencontros-workers to Azure Function App (boraencontros-workers)
      uses: Azure/functions-action@v1
      with:
        app-name: 'boraencontros-workers'
        slot-name: 'Production'
        package: ${{env.DOTNET_ROOT}}/boraencontros-workers